import Head from 'next/head'

async function getPages() {
  const wordpress_api_url = "http://localhost:8000/graphql"
  const pages = await fetch(wordpress_api_url, {
    method: 'POST',
    headers: {
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      query: `
        {
          pages {
            edges {
              node {
                slug
                authorId
                content
              }
            }
          }
        }
      `
    })
  }).then((res) => res.json());
  
  return {
    props: {
      pages
    }
  }
}

export default function Home() {
  console.log(getPages());
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  )
}
