import Head from 'next/head'

async function getPages() {
  const pages = await fetch(process.env.WORDPRESS_API_URL, {
    method: 'POST',
    headers: {
      "Content-Type": "application/json"
    },
    body: JSON.stringify({
      query: `
        {
          pages {
            edges {
              node {
                slug
                authorId
                content
              }
            }
          }
        }
      `
    })
  })
    .then((res) => res.json())
  
  // This pages function has the reult after index is rendered and loaded,
  // find a solution to get the data before the main page is loaded in the browser
  return pages
}

export default function Home() {
  const pages = getPages()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <hr />
    </>
  )
}
