import Head from 'next/head'

import parse from 'html-react-parser'

export async function getStaticProps() {
  const homePage = await fetch(process.env.WORDPRESS_API_URL, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json'
    },
    body: JSON.stringify({
      query: `
        {
          page(id: "/home", idType:URI) {
            slug
            date
            title
            content
          }
        }
      `
    })
  }).then((res) => res.json())

  return {
    props: {
      homePage,
    },
  }
}

export default function Home({ homePage }) {
  const slug = homePage.data.page.slug
  const date = homePage.data.page.date
  const title = homePage.data.page.title
  const content = homePage.data.page.content

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <hr />
      <div className="flex flex-col items-center p-[5em]">
        <h1>Home Page content loaded at build time in nextjs</h1>
        <br />
        <div>
          SLUG: { slug }
        </div>
        <br />
        <div>
          DATE: { date }
        </div>
        <br />
        <div>
          TITLE: { title }
        </div>
        <br />
        <div>
          CONTENT: { parse( content ) }
        </div>
      </div>
    </>
  )
}
