version: '3'

services:
  dbs:
    container_name: database
    image:  mysql:8.0
    volumes:
      - ./dbs:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD:  password
    ports:
      - "3306:3306"
    networks:
      - wpsite

  php:
    container_name: phpmyadmin
    depends_on:
      - dbs
    image: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: dbs
      MYSQL_ROOT_PASSWORD: password
    networks:
      - wpsite

  cms:
    container_name: wordpress
    depends_on:
      - dbs
    image:  wordpress:latest
    ports:
      - "8000:80"
    restart: always
    volumes:
      - ./cms:/var/www/html
    environment:
      WORDPRESS_DB_HOST:  dbs
      WORDPRESS_DB_USER:  wordpress
      WORDPRESS_DB_PASSWORD:  password
      WORDPRESS_DB_NAME:  wordpress
    networks:
      - wpsite

  # app:

networks:
  wpsite:
